apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-qnbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-qnbe
    app.kubernetes.io/part-of: accounting
  name: java-springboot-hello-qnbe
  namespace: burrzinga-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: java-springboot-hello-qnbe
    weight: null
status: {}
